services:
  frontend-build:
    profiles: ["frontend-build"]
    image: node:23
    working_dir: /app
    container_name: frontend-build
    volumes:
      - .:/app

  caddy:
    image: caddy:latest
    profiles: ["caddy"]
    container_name: caddy
    restart: unless-stopped
    environment:
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./dist:/home/dist
    networks:
      - caddy-network

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy-network:
    driver: bridge
